# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: 'npm'
    directory: '/web'
    schedule:
      interval: 'weekly'
